### ISSUE TITLE
[Slack] Github 봇 알림 안 오는 이슈 발생 공유의 건

### ISSUE THREAD

**Issue by ddol82** [ddol82/HealingDog-SpringBoot#4]
**Describe the bug**
Slack에 Github 봇을 추가 후 현재 리포지토리를 subscribe까지 완료했습니다.
게시자의 경우 알림이 오는 것을 확인했지만 다른 팀원의 활동에 대한 알림이 오지 않고 있습니다.

**To Reproduce**
`/github subscribe ddol82/HealingDog-SpringBoot` 으로 등록했기 때문에 다음에 대해 알림을 표시하고 있습니다.
1. issues
2. pulls
3. commits
4. releases
5. deployments

다음에 대한 알림은 표시하지 않고 있습니다.
1. reviews
2. comments
3. branches
4. discussions
5. workflows

**Expected behavior**
Slack 내 Github 봇이 팀원에 대한 활동도 알림으로 띄워주어야 합니다.

**Operating Environment**
 - OS: Windows
 - Browser Chrome
 - Version 1.0

**Comment by spacekingdom** [comment]
test

**Comment by spacekingdom** [comment]
close issues test

**Comment by spacekingdom** [comment]
test

**Comment by ddol82** [comment]
issut close 시 알림 오는 것 확인했습니다.

/github subscribe 리포지토리 comments
명령어로 댓글까지 오픈하였지만 알림이 오지 않습니다.
근데 이건 저도 안 가네요.

**Comment by spacekingdom** [comment]
test

**Comment by spacekingdom** [comment]
test

**Comment by spacekingdom** [comment]
test

**Comment by LeeJongHo96** [comment]
test comment

**Comment by LeeJongHo96** [comment]
c

**Comment by ddol82** [comment]
이슈 알림 확인했습니다.
여전히 일반 댓글이 아닌 close with issue에 의해서만 comment 알림이 오네요.

**Comment by ddol82** [comment]
test

**Comment by ddol82** [comment]
개인 커밋의 경우 기존처럼 알림이 오지 않고, PR 요청 시 알림이 오는 기존의 형식을 계속해서 이용하도록 하고, 추가적으로 review 알림도 추가함을 알리며 이슈를 닫습니다.
