### ISSUE TITLE
security yml 파일 어플리케이션 yml파일 연결

### ISSUE THREAD

**Issue by kimseonjung** [ddol82/HealingDog-SpringBoot#9]
**문제와 관련된 요청 또는 현상**
보안을 위해  gitignore 으로 뺴놓은 jwt secret 키값(application-security.yml )을 application.yml 과 연결하여 jwt TokenProvider까지 연결하는법

**해결을 위한 제안**
해결완료
config:
 import:
 - classpath: / yml파일 로 경로를 지정해주면된다

**해결을 위해 고려했던 대안책**

**그 외 기타사항**

**Comment by ddol82** [comment]
application.yml 파일 내 설정에서 spring: config: import : - classpath:/민감정보.yml 구문을 통해 파일을 연결했다는 걸 짧게 코멘트로 요약 후 닫아주세요.
